import React, { useState, useEffect, useCallback } from 'react';
import MainPlaylistCard from './components/MainPlaylistCard';
import RefineSection from './components/RefineSection';
import { getForYouPlaylist, getRefinedPlaylist } from './services/geminiService';
import { Playlist, RefineCategory } from './types';
import { MusicNoteIcon } from './components/icons';

const App: React.FC = () => {
  const [mainPlaylist, setMainPlaylist] = useState<Playlist | null>(null);
  const [isLoadingMain, setIsLoadingMain] = useState<boolean>(true);
  
  const [refinedPlaylists, setRefinedPlaylists] = useState<Partial<Record<RefineCategory, Playlist>>>({});
  const [loadingStates, setLoadingStates] = useState<Partial<Record<RefineCategory, boolean>>>({});

  useEffect(() => {
    const fetchMainPlaylist = async () => {
      setIsLoadingMain(true);
      const playlist = await getForYouPlaylist();
      setMainPlaylist(playlist);
      setIsLoadingMain(false);
    };

    fetchMainPlaylist();
  }, []);

  const handleRefine = useCallback(async (category: RefineCategory) => {
    setLoadingStates(prev => ({ ...prev, [category]: true }));
    const playlist = await getRefinedPlaylist(category);
    setRefinedPlaylists(prev => ({ ...prev, [category]: playlist }));
    setLoadingStates(prev => ({ ...prev, [category]: false }));
  }, []);

  return (
    <div className="min-h-screen bg-slate-900 text-white font-sans">
      <div 
        className="absolute top-0 left-0 w-full h-full bg-cover bg-center opacity-10"
        style={{backgroundImage: 'url(https://picsum.photos/seed/musicbg/1920/1080)'}}
      ></div>
      <div className="relative z-10 container mx-auto p-4 md:p-8">
        <header className="flex items-center gap-4 mb-8">
          <div className="p-2 bg-cyan-400/20 rounded-lg">
            <MusicNoteIcon className="w-8 h-8 text-cyan-400" />
          </div>
          <h1 className="text-4xl font-extrabold tracking-tighter bg-clip-text text-transparent bg-gradient-to-r from-slate-200 to-slate-400">
            AI Music Recommender
          </h1>
        </header>

        <main>
          <p className="text-slate-300 text-lg mb-6 max-w-2xl">
            Your personalized playlist, generated by AI. Discover music from the last decade, curated just for you.
          </p>
          <MainPlaylistCard playlist={mainPlaylist} isLoading={isLoadingMain} />
          <RefineSection onRefine={handleRefine} refinedPlaylists={refinedPlaylists} loadingStates={loadingStates} />
        </main>
        
        <footer className="text-center text-slate-500 mt-12 py-4">
            <p>Powered by Google Gemini. UI crafted by a world-class React engineer.</p>
        </footer>
      </div>
    </div>
  );
};

export default App;